apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-demo
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/jiaolici/kubectl-demo/releases/download/v0.1.0/kubectl-demo_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-demo"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-demo"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/jiaolici/kubectl-demo/releases/download/v0.1.0/kubectl-demo_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-demo"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-demo"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/jiaolici/kubectl-demo/releases/download/v0.1.0/kubectl-demo_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-demo.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-demo.exe"
  shortDescription: A new plugin
  homepage: https://github.com/jiaolici/kubectl-demo
  caveats: |
    Usage:
      $ kubectl kubectl-demo

    For additional options:
      $ kubectl kubectl-demo --help
      or https://github.com/jiaolici/kubectl-demo/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
